export const videos = [
  {
    _id: 1,
    title: "React crash course",
    video: "w7ejDZ8SWv8",
    views: 864524,
    duration: "1:48:48",
    creator: "Free Code Camp",
    category: "React",
    uploadDate: new Date(2018, 11, 24, 10, 33, 30, 0),
    description: `Get started with React in this crash course. We will be building a task tracker app and look at components, props, state, hooks, working with an API and more. React (also known as React.js or ReactJS) is a free and open-source front-end JavaScript library for building user interfaces based on UI components. It is maintained by Meta (formerly Facebook) and a community of individual developers and companies. React can be used as a base in the development of single-page, mobile, or server-rendered applications with frameworks like Next.js. However, React is only concerned with state management and rendering that state to the DOM, so creating React applications usually requires the use of additional libraries for routing, as well as certain client-side functionality.`,
  },
  {
    _id: 2,
    title: "HTML and CSS full course",
    video: "cyuzt1Dp8X8",
    views: 744258,
    duration: "4:55:13",
    creator: "Brocode",
    category: "HTML",
    uploadDate: new Date(2019, 1, 4, 10, 13, 30, 0),
    description: `The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.
    Web browsers receive HTML documents from a web server or from local storage and render the documents into multimedia web pages. HTML describes the structure of a web page semantically and originally included cues for the appearance of the document.`,
  },
  {
    _id: 3,
    title: "NodeJS Beginner's Guide",
    video: "ENrzD9HAZK4",
    views: 133003,
    duration: "16:20",
    creator: "Fireship",
    category: "NodeJS",
    uploadDate: new Date(2016, 1, 24, 11, 13, 30, 0),
    description: `Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser. Node.js lets developers use JavaScript to write command line tools and for server-side scripting—running scripts server-side to produce dynamic web page content before the page is sent to the user's web browser. Consequently, Node.js represents a "JavaScript everywhere" paradigm, unifying web-application development around a single programming language, rather than different languages for server-side and client-side scripts.
    Node.js has an event-driven architecture capable of asynchronous I/O. These design choices aim to optimize throughput and scalability in web applications with many input/output operations, as well as for real-time Web applications (e.g., real-time communication programs and browser games).`,
  },
  {
    _id: 4,
    title: "Advance React patterns",
    video: "MfIoAG3e7p4",
    views: 421053,
    duration: "58:04",
    creator: "codedamn",
    category: "React",
    uploadDate: new Date(2020, 4, 21, 12, 13, 30, 0),
    description: `Get started with React in this crash course. We will be building a task tracker app and look at components, props, state, hooks, working with an API and more. React (also known as React.js or ReactJS) is a free and open-source front-end JavaScript library for building user interfaces based on UI components. It is maintained by Meta (formerly Facebook) and a community of individual developers and companies. React can be used as a base in the development of single-page, mobile, or server-rendered applications with frameworks like Next.js. However, React is only concerned with state management and rendering that state to the DOM, so creating React applications usually requires the use of additional libraries for routing, as well as certain client-side functionality.`,
  },
  {
    _id: 5,
    title: "HTML Important Concepts",
    video: "HJ0-fUJ-2F0",
    views: 323494,
    duration: "14:37",
    creator: "Kevin Powell",
    category: "HTML",
    uploadDate: new Date(2019, 10, 29, 1, 13, 30, 0),
    description: `The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.
    Web browsers receive HTML documents from a web server or from local storage and render the documents into multimedia web pages. HTML describes the structure of a web page semantically and originally included cues for the appearance of the document.`,
  },
  {
    _id: 6,
    title: "What is JS ?",
    video: "OSWppEa2Zac",
    views: 230589,
    duration: "5:05",
    creator: "WP",
    category: "Javascript",
    uploadDate: new Date(2014, 1, 24, 10, 13, 30, 0),
    description: `JavaScript often abbreviated JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. Over 97% of websites use JavaScript on the client side for web page behavior, often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users' devices.
    JavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript standard.It has dynamic typing, prototype-based object-orientation, and first-class functions. It is multi-paradigm, supporting event-driven, functional, and imperative programming styles. It has application programming interfaces (APIs) for working with text, dates, regular expressions, standard data structures, and the Document Object Model (DOM)`,
  },
  {
    _id: 7,
    title: "MongoDB in 30 minutes",
    video: "pWbMrx5rVBE",
    views: 256080,
    duration: "32:12",
    creator: "Traversy Media",
    category: "MongoDB",
    uploadDate: new Date(2022, 1, 24, 10, 13, 30, 0),
    description: `MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License (SSPL) which is deemed non-free by several distributions.`,
  },
  {
    _id: 8,
    title: "What is event loop ?",
    video: "8aGhZQkoFbQ",
    views: 32059500,
    duration: "26:53",
    creator: "JSConf",
    category: "Javascript",
    uploadDate: new Date(2018, 8, 20, 10, 13, 30, 0),
    description: `JavaScript often abbreviated JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. Over 97% of websites use JavaScript on the client side for web page behavior, often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users' devices.
    JavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript standard.It has dynamic typing, prototype-based object-orientation, and first-class functions. It is multi-paradigm, supporting event-driven, functional, and imperative programming styles. It has application programming interfaces (APIs) for working with text, dates, regular expressions, standard data structures, and the Document Object Model (DOM)`,
  },
  {
    _id: 9,
    title: "MongoDB in 100sec",
    video: "-bt_y4Loofg",
    views: 343505,
    duration: "2:27",
    creator: "Fireship",
    category: "MongoDB",
    uploadDate: new Date(2016, 6, 2, 2, 30, 30, 0),
    description: `MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License (SSPL) which is deemed non-free by several distributions.`,
  },
  {
    _id: 10,
    title: "NodeJS full course",
    video: "Oe421EPjeBE",
    views: 365322,
    duration: "8:16:47",
    creator: "Free Code Camp",
    category: "NodeJS",
    uploadDate: new Date(2022, 3, 27, 5, 13, 30, 0),
    description: `Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser. Node.js lets developers use JavaScript to write command line tools and for server-side scripting—running scripts server-side to produce dynamic web page content before the page is sent to the user's web browser. Consequently, Node.js represents a "JavaScript everywhere" paradigm, unifying web-application development around a single programming language, rather than different languages for server-side and client-side scripts.
    Node.js has an event-driven architecture capable of asynchronous I/O. These design choices aim to optimize throughput and scalability in web applications with many input/output operations, as well as for real-time Web applications (e.g., real-time communication programs and browser games).`,
  },
  {
    _id: 11,
    title: "What is MongoDB ?",
    video: "SnqPyqRh4r4",
    views: 143505,
    duration: "6:32",
    creator: "Simplilearn",
    category: "MongoDB",
    uploadDate: new Date(2021, 6, 2, 2, 30, 30, 0),
    description: `MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License (SSPL) which is deemed non-free by several distributions.`,
  },
  {
    _id: 12,
    title: "What is React ?",
    video: "N3AkSS5hXMA",
    views: 271524,
    duration: "4:33",
    creator: "Mosh",
    category: "React",
    uploadDate: new Date(2019, 3, 17, 10, 33, 30, 0),
    description: `Get started with React in this crash course. We will be building a task tracker app and look at components, props, state, hooks, working with an API and more. React (also known as React.js or ReactJS) is a free and open-source front-end JavaScript library for building user interfaces based on UI components. It is maintained by Meta (formerly Facebook) and a community of individual developers and companies. React can be used as a base in the development of single-page, mobile, or server-rendered applications with frameworks like Next.js. However, React is only concerned with state management and rendering that state to the DOM, so creating React applications usually requires the use of additional libraries for routing, as well as certain client-side functionality.`,
  },
  {
    _id: 13,
    title: "HTML in 10 minutes",
    video: "MDLn5-zSQQI",
    views: 271524,
    duration: "9:33",
    creator: "Mosh",
    category: "HTML",
    uploadDate: new Date(2019, 3, 17, 10, 33, 30, 0),
    description: `The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.
    Web browsers receive HTML documents from a web server or from local storage and render the documents into multimedia web pages. HTML describes the structure of a web page semantically and originally included cues for the appearance of the document.`,
  },
  {
    _id: 14,
    title: "Learn Javascript - Full course",
    video: "o1IaduQICO0",
    views: 171524,
    duration: "3:32:35",
    creator: "Edureka",
    category: "Javascript",
    uploadDate: new Date(2019, 3, 17, 10, 33, 30, 0),
    description: `JavaScript often abbreviated JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. Over 97% of websites use JavaScript on the client side for web page behavior, often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users' devices.
    JavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript standard.It has dynamic typing, prototype-based object-orientation, and first-class functions. It is multi-paradigm, supporting event-driven, functional, and imperative programming styles. It has application programming interfaces (APIs) for working with text, dates, regular expressions, standard data structures, and the Document Object Model (DOM)`,
  },
  {
    _id: 15,
    title: "What is NodeJS",
    video: "uVwtVBpw7RQ",
    views: 65322,
    duration: "3:43",
    creator: "Mosh",
    category: "NodeJS",
    uploadDate: new Date(2020, 3, 27, 5, 13, 30, 0),
    description: `Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser. Node.js lets developers use JavaScript to write command line tools and for server-side scripting—running scripts server-side to produce dynamic web page content before the page is sent to the user's web browser. Consequently, Node.js represents a "JavaScript everywhere" paradigm, unifying web-application development around a single programming language, rather than different languages for server-side and client-side scripts.
    Node.js has an event-driven architecture capable of asynchronous I/O. These design choices aim to optimize throughput and scalability in web applications with many input/output operations, as well as for real-time Web applications (e.g., real-time communication programs and browser games).`,
  },
];
